apiVersion: apps/v1
kind: Deployment
metadata:
  name: odprti-racuni-obcine-deployment
  labels:
    app: odprti-racuni-obcine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odprti-racuni-obcine
  template:
    metadata:
      labels:
        app: odprti-racuni-obcine
    spec:
      volumes:
        - name: odprti-racuni-obcine-shared-storage
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: odprti-racuni-obcine
          volumeMounts:
            - name: odprti-racuni-obcine-shared-storage
              mountPath: /pvc
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: odprti_racuni_obcine.settings
            - name: DJANGO_STATIC_ROOT
              value: "/pvc/static"
          envFrom:
            - secretRef:
                name: odprti-racuni-obcine-credentials
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
            limits:
              memory: 200Mi
              cpu: 200m
        - name: migrate
          image: odprti-racuni-obcine
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: odprti_racuni_obcine.settings
          envFrom:
            - secretRef:
                name: odprti-racuni-obcine-credentials
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
            limits:
              memory: 200Mi
              cpu: 200m
      containers:
        - name: odprti-racuni-obcine
          image: odprti-racuni-obcine
          volumeMounts:
            - name: odprti-racuni-obcine-shared-storage
              mountPath: /pvc
          command:
            - gunicorn
            - odprti_racuni_obcine.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
            - --workers
            - "1"
            - --threads
            - "3"
            - --timeout
            - "120"
          ports:
            - containerPort: 8000
          envFrom:
              - secretRef:
                  name: odprti-racuni-obcine-credentials
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: odprti_racuni_obcine.settings
            - name: DJANGO_STATIC_ROOT
              value: "/pvc/static"
            - name: DJANGO_STATIC_URL_BASE
              value: "https://files.odprtiracuniobcine.lb.djnd.si/static/"
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 400Mi
              cpu: 200m
        - name: odprti-racuni-obcine-nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          image: nginx:alpine
          volumeMounts:
            - name: odprti-racuni-obcine-shared-storage
              mountPath: /usr/share/nginx/html
