# Generated by Django 4.0.5 on 2023-05-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obcine', '0003_task'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyexpensedocument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyrevenuedocument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plannedexpensedocument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plannedrevenuedocument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='yearlyexpensedocument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='yearlyrevenuedocument',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='monthlyexpensedocument',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='monthlyexpensedocument',
            name='year',
        ),
        migrations.RemoveField(
            model_name='monthlyrevenuedocument',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='monthlyrevenuedocument',
            name='year',
        ),
        migrations.RemoveField(
            model_name='plannedexpensedocument',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='plannedexpensedocument',
            name='year',
        ),
        migrations.RemoveField(
            model_name='plannedrevenuedocument',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='plannedrevenuedocument',
            name='year',
        ),
        migrations.RemoveField(
            model_name='yearlyexpensedocument',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='yearlyexpensedocument',
            name='year',
        ),
        migrations.RemoveField(
            model_name='yearlyrevenuedocument',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='yearlyrevenuedocument',
            name='year',
        ),
    ]
