# Generated by Django 4.0.5 on 2023-05-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obcine", "0007_municipalityfinancialyear_rebalans_date_of_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedexpense",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="obcine.plannedexpensedocument",
            ),
        ),
        migrations.AlterField(
            model_name="plannedrevenue",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="obcine.plannedrevenuedocument",
            ),
        ),
    ]
