# Generated by Django 4.0.5 on 2023-05-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obcine', '0009_alter_municipality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='financial_years',
            field=models.ManyToManyField(through='obcine.MunicipalityFinancialYear', to='obcine.financialyear'),
        ),
        migrations.AlterField(
            model_name='municipalityfinancialyear',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipalityfinancialyears', to='obcine.financialyear'),
        ),
        migrations.AlterField(
            model_name='municipalityfinancialyear',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipalityfinancialyears', to='obcine.municipality'),
        ),
    ]
