# Generated by Django 4.0.5 on 2023-05-12 13:48

from django.db import migrations, models
import obcine.models


class Migration(migrations.Migration):

    dependencies = [
        ('obcine', '0011_alter_monthlyexpensedocument_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name="Organization's link"),
        ),
        migrations.AddField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(null=True, upload_to='', validators=[obcine.models.image_validator, obcine.models.validate_image_extension], verbose_name='Logo'),
        ),
    ]
