# Generated by Django 4.0.5 on 2023-05-12 13:51

from django.db import migrations, models
import obcine.models


class Migration(migrations.Migration):

    dependencies = [
        ('obcine', '0012_municipality_link_municipality_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[obcine.models.image_validator, obcine.models.validate_image_extension], verbose_name='Logo'),
        ),
    ]
