# Generated by Django 4.0.5 on 2023-06-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obcine', '0018_alter_monthlyexpensedocument_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrevenue',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='monthlyexpensedocument',
            name='timestamp',
            field=models.DateField(blank=True, null=True, verbose_name='Datum obdelave podatkov'),
        ),
        migrations.AddField(
            model_name='monthlyrevenuedocument',
            name='timestamp',
            field=models.DateField(blank=True, null=True, verbose_name='Datum obdelave podatkov'),
        ),
    ]
