# Generated by Django 4.0.5 on 2023-09-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obcine', '0019_remove_monthlyrevenue_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='yearlyexpensedocument',
            name='timestamp',
            field=models.DateField(blank=True, null=True, verbose_name='Datum obdelave podatkov'),
        ),
        migrations.AddField(
            model_name='yearlyrevenuedocument',
            name='timestamp',
            field=models.DateField(blank=True, null=True, verbose_name='Datum obdelave podatkov'),
        ),
    ]
