# Generated by Django 4.0.5 on 2023-11-21 17:21

from django.db import migrations, models
from django.utils.text import slugify
import re


def forwards_func(apps, schema_editor):
    Municipality = apps.get_model("obcine", "Municipality")
    db_alias = schema_editor.connection.alias

    for municipality in Municipality.objects.using(db_alias).all():
        slug = slugify(municipality.name)
        slug = re.sub(r"mestna-obcina-", "", slug)
        slug = re.sub(r"obcina-", "", slug)
        municipality.slug = slug
        municipality.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('obcine', '0026_municipality_slug'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
